# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# RUN SCA ONLY

trigger:
- main

pool: Default

steps:
- script: |
    if not defined P_BASE_NAMECLASSPATH (
        set P_BASE_NAMECLASSPATH=default_value
        echo P_BASE_NAMECLASSPATH is set to default value: %P_BASE_NAMECLASSPATH%.
    ) else (
        echo P_BASE_NAMECLASSPATH is defined as %P_BASE_NAMECLASSPATH%.
    )
  displayName: 'Set default value for P_BASE_NAMECLASSPATH if not defined'

- script: .\gradlew.bat wrapper --gradle-version 8.8
  displayName: 'Run Gradle Wrapper'
- task: CmdLine@2
  inputs:
    script: |
      set ANDROID_HOME=$(ANDROID_HOME)
      set ANDROID_SDK_ROOT=$(ANDROID_SDK_ROOT)
- task: CmdLine@2
  inputs:
    script: 'echo %ANDROID_HOME%'
- task: FortifySCA@7
  inputs:
    applicationType: 'other'
    buildToolOptions: 'gradlew clean build'
    fortifyBuildId: 'gradle_j'
    scaVerbose: true
    scaDebug: true
    fortifyScanType: 'ScanCentralScan'
    scanCentralFortifyServerName: 'SSC'
    scanCentralRunFortifyUpload: true
    scanCentralFortifyApplicationIdentifierType: 'byId'
    scanCentralFortifyApplicationVersionId: '10020'
    fortifyBuildFailureCriteria: '[fortify priority order]:critical'
    taskResultForBuildFailureCriteria: 'FAIL'
